name: Release
on:
  push:
    tags: ["v*"]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --locked --target ${{ matrix.target }} -p makina
      - name: Package
        run: tar -czf makina-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release makina
      - uses: softprops/action-gh-release@v2
        with:
          files: makina-${{ matrix.target }}.tar.gz
